In [ ]:
# Import Panda

In [1]:
import pandas as pd

In [ ]:
# Fetch Files

In [2]:
sales = pd.read_csv('sales.csv')
products = pd.read_csv('products.csv')
inventory = pd.read_csv('inventory.csv')

In [3]:
sales

      order_ID        date product_ID  units_sold  selling_price  revenue
0         1000  23-02-2024       P030           8            438     3504
1         1001  27-03-2024       P033           9            261     2349
2         1002  08-05-2024       P009           9            279     2511
3         1003  26-05-2024       P047           2            369      738
4         1004  05-05-2024       P001           9            418     3762
...        ...         ...        ...         ...            ...      ...
4995      5995  28-06-2024       P019           1            465      465
4996      5996  17-04-2024       P002           4            515     2060
4997      5997  22-02-2024       P022           7            648     4536
4998      5998  07-05-2024       P020           9            581     5229
4999      5999  28-06-2024       P033           9            261     2349

[5000 rows x 6 columns]

In [4]:
products

,product_ID,product_name,category,cost_price,selling_price
0,P001,Wireless Mouse,Electronics,202,418
1,P002,Mechanical Keyboard,Electronics,448,515
2,P003,Bluetooth Speaker,Electronics,370,551
3,P004,USB-C Charger,Electronics,206,344
4,P005,LED Monitor 24 inch,Electronics,171,280
5,P006,Gaming Headset,Electronics,288,351
6,P007,External Hard Drive 1TB,Electronics,120,411
7,P008,Smartphone Stand,Electronics,202,501
8,P009,Laptop Backpack,Electronics,221,279
9,P010,Fitness Tracker,Electronics,314,453
10,P011,Men's Casual Shirt,Clothing,430,532
11,P012,Women's Kurti,Clothing,187,366
12,P013,Denim Jeans,Clothing,472,605
13,P014,Sports Shoes,Clothing,199,340
14,P015,Leather Wallet,Clothing,459,619
15,P016,Sunglasses,Clothing,251,488
16,P017,Towel Set,Clothing,230,478
17,P018,Bed Sheet,Clothing,249,470
18,P019,Pillow Cover,Clothing,408,465
19,P020,Blanket,Clothing,357,581
20,P021,Kitchen Knife Set,Home & Kitchen,443,527
21,P022,Non-stick Frying Pan,Home & Kitchen,393,648
22,P023,Electric Kettle,Home & Kitchen,485,615
23,P024,Mixer Grinder,Home & Kitchen,291,504
24,P025,Rice Cooker,Home & Kitchen,376,475
25,P026,Water Bottle,Home & Kitchen,260,413
26,P027,Lunch Box,Home & Kitchen,413,594
27,P028,Coffee Mug,Home & Kitchen,121,172
28,P029,Desk Organizer,Home & Kitchen,352,535
29,P030,Table Lamp,Home & Kitchen,335,438
30,P031,Wall Clock,Home & Kitchen,444,599
31,P032,Office Chair,Home & Kitchen,148,201
32,P033,Organic Rice 5kg,Grocery,158,261
33,P034,Wheat Flour 10kg,Grocery,269,539
34,P035,Cooking Oil 1L,Grocery,287,527
35,P036,Sugar 1kg,Grocery,370,565
36,P037,Salt Pack,Grocery,289,556
37,P038,Tea Powder,Grocery,274,367
38,P039,Instant Coffee,Grocery,150,361
39,P040,Biscuits Pack,Grocery,463,714
40,P041,Chocolate Box,Grocery,154,393
41,P042,Toothpaste,Personal Care,343,620
42,P043,Shampoo Bottle,Personal Care,419,482
43,P044,Bath Soap,Personal Care,230,374
44,P045,Hand Sanitizer,Personal Care,406,503
45,P046,Face Wash,Personal Care,234,298
46,P047,Mobile Charger,Electronics,120,369
47,P048,Power Bank,Electronics,428,683

In [5]:
inventory

   product_ID  stock_available  Lead_Time                    supplier
0        P001              264          9      D-Mart Supply Services
1        P002              301          6      Amazon Wholesale India
2        P003              239          4    ITC Distribution Network
3        P004              345          5  Tata Consumer Distribution
4        P005              262          9     Future Retail Suppliers
5        P006              257          7    Metro Cash & Carry India
6        P007              286          4   Aditya Birla Supply Chain
7        P008              387          4    ITC Distribution Network
8        P009              416          2          Flipkart Wholesale
9        P010              102          4     Future Retail Suppliers
10       P011              329          6      D-Mart Supply Services
11       P012              459          8    Metro Cash & Carry India
12       P013              266          7      D-Mart Supply Services
13       P014              301          4      Reliance Retail Supply
14       P015              237          2      Reliance Retail Supply
15       P016              429          6    Metro Cash & Carry India
16       P017               90          3    Metro Cash & Carry India
17       P018              206          8          Flipkart Wholesale
18       P019               64          8    Metro Cash & Carry India
19       P020              350          7      Amazon Wholesale India
20       P021              114          8      D-Mart Supply Services
21       P022              394          4    ITC Distribution Network
22       P023              376          2    BigBasket Vendor Network
23       P024               58          8    Metro Cash & Carry India
24       P025              393          8   Aditya Birla Supply Chain
25       P026              178          3      Reliance Retail Supply
26       P027              185          3      Amazon Wholesale India
27       P028              112          5     Future Retail Suppliers
28       P029              188          6    BigBasket Vendor Network
29       P030              130          4    ITC Distribution Network
30       P031              441          8    BigBasket Vendor Network
31       P032              212          9    Metro Cash & Carry India
32       P033              468          8          Flipkart Wholesale
33       P034              338          2      Reliance Retail Supply
34       P035              428          5      Reliance Retail Supply
35       P036              310          6     Future Retail Suppliers
36       P037              280          9          Flipkart Wholesale
37       P038               90          5      D-Mart Supply Services
38       P039               77          7  Tata Consumer Distribution
39       P040              184          6      Amazon Wholesale India
40       P041              250          8      Reliance Retail Supply
41       P042              377          8   Aditya Birla Supply Chain
42       P043              317          6      Reliance Retail Supply
43       P044              467          8    BigBasket Vendor Network
44       P045               82          4      Reliance Retail Supply
45       P046               97          6      Reliance Retail Supply
46       P047              456          5  Tata Consumer Distribution
47       P048              111          6  Tata Consumer Distribution

In [ ]:
# Check null / missing values

In [6]:
print('missing values:\n', sales.isnull().sum())

missing values:
 order_ID         0
date             0
product_ID       0
units_sold       0
selling_price    0
revenue          0
dtype: int64

In [7]:
print('missing values:\n', products.isnull().sum())

missing values:
 product_ID       0
product_name     0
category         0
cost_price       0
selling_price    0
dtype: int64

In [8]:
print('missing values:\n', inventory.isnull().sum())

missing values:
 product_ID         0
stock_available    0
Lead_Time          0
supplier           0
dtype: int64

In [ ]:
# Identify duplicates

In [12]:
print('Duplicate values:\n', sales.duplicated().sum())

Duplicate values:
 0

In [13]:
print('Duplicate values:\n', products.duplicated().sum())

Duplicate values:
 0

In [14]:
print('Duplicate values:\n', inventory.duplicated().sum())

Duplicate values:
 0

In [ ]:
# Basic info for sales

In [15]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_ID       5000 non-null   int64
 1   date           5000 non-null   str
 2   product_ID     5000 non-null   str
 3   units_sold     5000 non-null   int64
 4   selling_price  5000 non-null   int64
 5   revenue        5000 non-null   int64
dtypes: int64(4), str(2)
memory usage: 234.5 KB

In [16]:
sales.describe()

          order_ID   units_sold  selling_price      revenue
count  5000.000000  5000.000000    5000.000000  5000.000000
mean   3499.500000     5.010200     467.604800  2346.392200
std    1443.520003     2.580354     123.216537  1396.352312
min    1000.000000     1.000000     172.000000   172.000000
25%    2249.750000     3.000000     369.000000  1188.000000
50%    3499.500000     5.000000     482.000000  2202.000000
75%    4749.250000     7.000000     556.000000  3321.000000
max    5999.000000     9.000000     714.000000  6426.000000

In [ ]:
# Basic info for products

In [17]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_ID     48 non-null     str
 1   product_name   48 non-null     str
 2   category       48 non-null     str
 3   cost_price     48 non-null     int64
 4   selling_price  48 non-null     int64
dtypes: int64(2), str(3)
memory usage: 2.0 KB

In [18]:
products.describe()

       cost_price  selling_price
count    48.00000      48.000000
mean    300.81250     466.250000
std     110.70464     125.110419
min     120.00000     172.000000
25%     205.00000     368.500000
50%     288.50000     480.000000
75%     406.50000     552.250000
max     485.00000     714.000000

In [ ]:
# Basic info for inventory

In [19]:
inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   product_ID       48 non-null     str
 1   stock_available  48 non-null     int64
 2   Lead_Time        48 non-null     int64
 3   supplier         48 non-null     str
dtypes: int64(2), str(2)
memory usage: 1.6 KB

In [20]:
inventory.describe()

       stock_available  Lead_Time
count        48.000000  48.000000
mean        264.645833   5.833333
std         126.991621   2.117137
min          58.000000   2.000000
25%         166.000000   4.000000
50%         265.000000   6.000000
75%         376.250000   8.000000
max         468.000000   9.000000

In [ ]:
# Fix Data Type

In [23]:
sales['date'] = pd.to_datetime(sales['date'])
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_ID       5000 non-null   int64
 1   date           5000 non-null   datetime64[us]
 2   product_ID     5000 non-null   str
 3   units_sold     5000 non-null   int64
 4   selling_price  5000 non-null   int64
 5   revenue        5000 non-null   int64
dtypes: datetime64[us](1), int64(4), str(1)
memory usage: 234.5 KB

In [ ]:
# Merge Tables

In [24]:
sales.merge(products, on = 'product_ID', how = 'left')

,order_ID,date,product_ID,units_sold,selling_price_x,revenue,product_name,category,cost_price,selling_price_y
0,1000,2024-02-23,P030,8,438,3504,Table Lamp,Home & Kitchen,335,438
1,1001,2024-03-27,P033,9,261,2349,Organic Rice 5kg,Grocery,158,261
2,1002,2024-05-08,P009,9,279,2511,Laptop Backpack,Electronics,221,279
3,1003,2024-05-26,P047,2,369,738,Mobile Charger,Electronics,120,369
4,1004,2024-05-05,P001,9,418,3762,Wireless Mouse,Electronics,202,418
...,...,...,...,...,...,...,...,...,...,...
4995,5995,2024-06-28,P019,1,465,465,Pillow Cover,Clothing,408,465
4996,5996,2024-04-17,P002,4,515,2060,Mechanical Keyboard,Electronics,448,515
4997,5997,2024-02-22,P022,7,648,4536,Non-stick Frying Pan,Home & Kitchen,393,648
4998,5998,2024-05-07,P020,9,581,5229,Blanket,Clothing,357,581
4999,5999,2024-06-28,P033,9,261,2349,Organic Rice 5kg,Grocery,158,261

In [25]:
sales.merge(products, on = 'product_ID', how = 'inner')

,order_ID,date,product_ID,units_sold,selling_price_x,revenue,product_name,category,cost_price,selling_price_y
0,1000,2024-02-23,P030,8,438,3504,Table Lamp,Home & Kitchen,335,438
1,1001,2024-03-27,P033,9,261,2349,Organic Rice 5kg,Grocery,158,261
2,1002,2024-05-08,P009,9,279,2511,Laptop Backpack,Electronics,221,279
3,1003,2024-05-26,P047,2,369,738,Mobile Charger,Electronics,120,369
4,1004,2024-05-05,P001,9,418,3762,Wireless Mouse,Electronics,202,418
...,...,...,...,...,...,...,...,...,...,...
4995,5995,2024-06-28,P019,1,465,465,Pillow Cover,Clothing,408,465
4996,5996,2024-04-17,P002,4,515,2060,Mechanical Keyboard,Electronics,448,515
4997,5997,2024-02-22,P022,7,648,4536,Non-stick Frying Pan,Home & Kitchen,393,648
4998,5998,2024-05-07,P020,9,581,5229,Blanket,Clothing,357,581
4999,5999,2024-06-28,P033,9,261,2349,Organic Rice 5kg,Grocery,158,261

In [29]:
df = sales.merge(products, on = 'product_ID', how = 'left')

In [32]:
print(df)

      order_ID       date product_ID  units_sold  selling_price_x  revenue  \
0         1000 2024-02-23       P030           8              438     3504
1         1001 2024-03-27       P033           9              261     2349
2         1002 2024-05-08       P009           9              279     2511
3         1003 2024-05-26       P047           2              369      738
4         1004 2024-05-05       P001           9              418     3762
...        ...        ...        ...         ...              ...      ...
4995      5995 2024-06-28       P019           1              465      465
4996      5996 2024-04-17       P002           4              515     2060
4997      5997 2024-02-22       P022           7              648     4536
4998      5998 2024-05-07       P020           9              581     5229
4999      5999 2024-06-28       P033           9              261     2349

              product_name        category  cost_price  selling_price_y
0               Table Lamp  Home & Kitchen         335              438
1         Organic Rice 5kg         Grocery         158              261
2          Laptop Backpack     Electronics         221              279
3           Mobile Charger     Electronics         120              369
4           Wireless Mouse     Electronics         202              418
...                    ...             ...         ...              ...
4995          Pillow Cover        Clothing         408              465
4996   Mechanical Keyboard     Electronics         448              515
4997  Non-stick Frying Pan  Home & Kitchen         393              648
4998               Blanket        Clothing         357              581
4999      Organic Rice 5kg         Grocery         158              261

[5000 rows x 10 columns]

In [33]:
df.head(10)

,order_ID,date,product_ID,units_sold,selling_price_x,revenue,product_name,category,cost_price,selling_price_y
0,1000,2024-02-23,P030,8,438,3504,Table Lamp,Home & Kitchen,335,438
1,1001,2024-03-27,P033,9,261,2349,Organic Rice 5kg,Grocery,158,261
2,1002,2024-05-08,P009,9,279,2511,Laptop Backpack,Electronics,221,279
3,1003,2024-05-26,P047,2,369,738,Mobile Charger,Electronics,120,369
4,1004,2024-05-05,P001,9,418,3762,Wireless Mouse,Electronics,202,418
5,1005,2024-05-09,P044,7,374,2618,Bath Soap,Personal Care,230,374
6,1006,2024-02-22,P035,5,527,2635,Cooking Oil 1L,Grocery,287,527
7,1007,2024-06-20,P011,7,532,3724,Men's Casual Shirt,Clothing,430,532
8,1008,2024-06-08,P034,9,539,4851,Wheat Flour 10kg,Grocery,269,539
9,1009,2024-06-08,P016,8,488,3904,Sunglasses,Clothing,251,488

In [37]:
df = df.merge(inventory, on = 'product_ID', how = 'left')
df

,order_ID,date,product_ID,units_sold,selling_price,revenue,product_name,category,cost_price,stock_available,Lead_Time,supplier
0,1000,2024-02-23,P030,8,438,3504,Table Lamp,Home & Kitchen,335,130,4,ITC Distribution Network
1,1001,2024-03-27,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale
2,1002,2024-05-08,P009,9,279,2511,Laptop Backpack,Electronics,221,416,2,Flipkart Wholesale
3,1003,2024-05-26,P047,2,369,738,Mobile Charger,Electronics,120,456,5,Tata Consumer Distribution
4,1004,2024-05-05,P001,9,418,3762,Wireless Mouse,Electronics,202,264,9,D-Mart Supply Services
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,5995,2024-06-28,P019,1,465,465,Pillow Cover,Clothing,408,64,8,Metro Cash & Carry India
4996,5996,2024-04-17,P002,4,515,2060,Mechanical Keyboard,Electronics,448,301,6,Amazon Wholesale India
4997,5997,2024-02-22,P022,7,648,4536,Non-stick Frying Pan,Home & Kitchen,393,394,4,ITC Distribution Network
4998,5998,2024-05-07,P020,9,581,5229,Blanket,Clothing,357,350,7,Amazon Wholesale India
4999,5999,2024-06-28,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale

In [38]:
print(df)

      order_ID       date product_ID  units_sold  selling_price  revenue  \
0         1000 2024-02-23       P030           8            438     3504
1         1001 2024-03-27       P033           9            261     2349
2         1002 2024-05-08       P009           9            279     2511
3         1003 2024-05-26       P047           2            369      738
4         1004 2024-05-05       P001           9            418     3762
...        ...        ...        ...         ...            ...      ...
4995      5995 2024-06-28       P019           1            465      465
4996      5996 2024-04-17       P002           4            515     2060
4997      5997 2024-02-22       P022           7            648     4536
4998      5998 2024-05-07       P020           9            581     5229
4999      5999 2024-06-28       P033           9            261     2349

              product_name        category  cost_price  stock_available  \
0               Table Lamp  Home & Kitchen         335              130
1         Organic Rice 5kg         Grocery         158              468
2          Laptop Backpack     Electronics         221              416
3           Mobile Charger     Electronics         120              456
4           Wireless Mouse     Electronics         202              264
...                    ...             ...         ...              ...
4995          Pillow Cover        Clothing         408               64
4996   Mechanical Keyboard     Electronics         448              301
4997  Non-stick Frying Pan  Home & Kitchen         393              394
4998               Blanket        Clothing         357              350
4999      Organic Rice 5kg         Grocery         158              468

      Lead_Time                    supplier
0             4    ITC Distribution Network
1             8          Flipkart Wholesale
2             2          Flipkart Wholesale
3             5  Tata Consumer Distribution
4             9      D-Mart Supply Services
...         ...                         ...
4995          8    Metro Cash & Carry India
4996          6      Amazon Wholesale India
4997          4    ITC Distribution Network
4998          7      Amazon Wholesale India
4999          8          Flipkart Wholesale

[5000 rows x 12 columns]

In [ ]:
# Rename and Drop

In [35]:
df = df.rename(columns={"selling_price_x": "selling_price"})
df = df.drop(columns=["selling_price_y"])

In [39]:
df

,order_ID,date,product_ID,units_sold,selling_price,revenue,product_name,category,cost_price,stock_available,Lead_Time,supplier
0,1000,2024-02-23,P030,8,438,3504,Table Lamp,Home & Kitchen,335,130,4,ITC Distribution Network
1,1001,2024-03-27,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale
2,1002,2024-05-08,P009,9,279,2511,Laptop Backpack,Electronics,221,416,2,Flipkart Wholesale
3,1003,2024-05-26,P047,2,369,738,Mobile Charger,Electronics,120,456,5,Tata Consumer Distribution
4,1004,2024-05-05,P001,9,418,3762,Wireless Mouse,Electronics,202,264,9,D-Mart Supply Services
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,5995,2024-06-28,P019,1,465,465,Pillow Cover,Clothing,408,64,8,Metro Cash & Carry India
4996,5996,2024-04-17,P002,4,515,2060,Mechanical Keyboard,Electronics,448,301,6,Amazon Wholesale India
4997,5997,2024-02-22,P022,7,648,4536,Non-stick Frying Pan,Home & Kitchen,393,394,4,ITC Distribution Network
4998,5998,2024-05-07,P020,9,581,5229,Blanket,Clothing,357,350,7,Amazon Wholesale India
4999,5999,2024-06-28,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale

In [40]:
df = df.rename(columns={"Lead_Time": "lead_time"})
df

,order_ID,date,product_ID,units_sold,selling_price,revenue,product_name,category,cost_price,stock_available,lead_time,supplier
0,1000,2024-02-23,P030,8,438,3504,Table Lamp,Home & Kitchen,335,130,4,ITC Distribution Network
1,1001,2024-03-27,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale
2,1002,2024-05-08,P009,9,279,2511,Laptop Backpack,Electronics,221,416,2,Flipkart Wholesale
3,1003,2024-05-26,P047,2,369,738,Mobile Charger,Electronics,120,456,5,Tata Consumer Distribution
4,1004,2024-05-05,P001,9,418,3762,Wireless Mouse,Electronics,202,264,9,D-Mart Supply Services
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,5995,2024-06-28,P019,1,465,465,Pillow Cover,Clothing,408,64,8,Metro Cash & Carry India
4996,5996,2024-04-17,P002,4,515,2060,Mechanical Keyboard,Electronics,448,301,6,Amazon Wholesale India
4997,5997,2024-02-22,P022,7,648,4536,Non-stick Frying Pan,Home & Kitchen,393,394,4,ITC Distribution Network
4998,5998,2024-05-07,P020,9,581,5229,Blanket,Clothing,357,350,7,Amazon Wholesale India
4999,5999,2024-06-28,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale

In [ ]:
# Feature Engineering

In [ ]:
# Total sales

In [59]:
df["Total_Sales_Product"] = df.groupby("product_ID")["units_sold"].transform("sum")

In [62]:
df = df.rename(columns={"Total_Sales_Product": "total_sales_product"})

In [63]:
df

,order_ID,date,product_ID,units_sold,selling_price,revenue,product_name,category,cost_price,stock_available,lead_time,supplier,daily_avg_sales,days_of_stock,total_sales_product
0,1000,2024-02-23,P030,8,438,3504,Table Lamp,Home & Kitchen,335,130,4,ITC Distribution Network,5.13,25.0,487
1,1001,2024-03-27,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06,92.0,501
2,1002,2024-05-08,P009,9,279,2511,Laptop Backpack,Electronics,221,416,2,Flipkart Wholesale,5.18,80.0,534
3,1003,2024-05-26,P047,2,369,738,Mobile Charger,Electronics,120,456,5,Tata Consumer Distribution,4.73,96.0,478
4,1004,2024-05-05,P001,9,418,3762,Wireless Mouse,Electronics,202,264,9,D-Mart Supply Services,5.05,52.0,475
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,5995,2024-06-28,P019,1,465,465,Pillow Cover,Clothing,408,64,8,Metro Cash & Carry India,5.28,12.0,533
4996,5996,2024-04-17,P002,4,515,2060,Mechanical Keyboard,Electronics,448,301,6,Amazon Wholesale India,5.13,59.0,600
4997,5997,2024-02-22,P022,7,648,4536,Non-stick Frying Pan,Home & Kitchen,393,394,4,ITC Distribution Network,5.42,73.0,537
4998,5998,2024-05-07,P020,9,581,5229,Blanket,Clothing,357,350,7,Amazon Wholesale India,4.96,71.0,526
4999,5999,2024-06-28,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06,92.0,501

In [ ]:
# Daily Average Sales

In [48]:
df['daily_avg_sales'] = df.groupby('product_ID')['units_sold'].transform('mean').round(2)
df

,order_ID,date,product_ID,units_sold,selling_price,revenue,product_name,category,cost_price,stock_available,lead_time,supplier,daily_avg_sales
0,1000,2024-02-23,P030,8,438,3504,Table Lamp,Home & Kitchen,335,130,4,ITC Distribution Network,5.13
1,1001,2024-03-27,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06
2,1002,2024-05-08,P009,9,279,2511,Laptop Backpack,Electronics,221,416,2,Flipkart Wholesale,5.18
3,1003,2024-05-26,P047,2,369,738,Mobile Charger,Electronics,120,456,5,Tata Consumer Distribution,4.73
4,1004,2024-05-05,P001,9,418,3762,Wireless Mouse,Electronics,202,264,9,D-Mart Supply Services,5.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,5995,2024-06-28,P019,1,465,465,Pillow Cover,Clothing,408,64,8,Metro Cash & Carry India,5.28
4996,5996,2024-04-17,P002,4,515,2060,Mechanical Keyboard,Electronics,448,301,6,Amazon Wholesale India,5.13
4997,5997,2024-02-22,P022,7,648,4536,Non-stick Frying Pan,Home & Kitchen,393,394,4,ITC Distribution Network,5.42
4998,5998,2024-05-07,P020,9,581,5229,Blanket,Clothing,357,350,7,Amazon Wholesale India,4.96
4999,5999,2024-06-28,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06

In [ ]:
# Days of Stock

In [52]:
df['days_of_stock'] = (df['stock_available'] / df['daily_avg_sales']).round()
df

,order_ID,date,product_ID,units_sold,selling_price,revenue,product_name,category,cost_price,stock_available,lead_time,supplier,daily_avg_sales,days_of_stock
0,1000,2024-02-23,P030,8,438,3504,Table Lamp,Home & Kitchen,335,130,4,ITC Distribution Network,5.13,25.0
1,1001,2024-03-27,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06,92.0
2,1002,2024-05-08,P009,9,279,2511,Laptop Backpack,Electronics,221,416,2,Flipkart Wholesale,5.18,80.0
3,1003,2024-05-26,P047,2,369,738,Mobile Charger,Electronics,120,456,5,Tata Consumer Distribution,4.73,96.0
4,1004,2024-05-05,P001,9,418,3762,Wireless Mouse,Electronics,202,264,9,D-Mart Supply Services,5.05,52.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,5995,2024-06-28,P019,1,465,465,Pillow Cover,Clothing,408,64,8,Metro Cash & Carry India,5.28,12.0
4996,5996,2024-04-17,P002,4,515,2060,Mechanical Keyboard,Electronics,448,301,6,Amazon Wholesale India,5.13,59.0
4997,5997,2024-02-22,P022,7,648,4536,Non-stick Frying Pan,Home & Kitchen,393,394,4,ITC Distribution Network,5.42,73.0
4998,5998,2024-05-07,P020,9,581,5229,Blanket,Clothing,357,350,7,Amazon Wholesale India,4.96,71.0
4999,5999,2024-06-28,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06,92.0

In [ ]:
# Inventory Turnover

In [67]:
df["inventory_turnover"] = (df["total_sales_product"] / df["stock_available"]).round()

In [68]:
df

,order_ID,date,product_ID,units_sold,selling_price,revenue,product_name,category,cost_price,stock_available,lead_time,supplier,daily_avg_sales,days_of_stock,total_sales_product,inventory_turnover
0,1000,2024-02-23,P030,8,438,3504,Table Lamp,Home & Kitchen,335,130,4,ITC Distribution Network,5.13,25.0,487,4.0
1,1001,2024-03-27,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06,92.0,501,1.0
2,1002,2024-05-08,P009,9,279,2511,Laptop Backpack,Electronics,221,416,2,Flipkart Wholesale,5.18,80.0,534,1.0
3,1003,2024-05-26,P047,2,369,738,Mobile Charger,Electronics,120,456,5,Tata Consumer Distribution,4.73,96.0,478,1.0
4,1004,2024-05-05,P001,9,418,3762,Wireless Mouse,Electronics,202,264,9,D-Mart Supply Services,5.05,52.0,475,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,5995,2024-06-28,P019,1,465,465,Pillow Cover,Clothing,408,64,8,Metro Cash & Carry India,5.28,12.0,533,8.0
4996,5996,2024-04-17,P002,4,515,2060,Mechanical Keyboard,Electronics,448,301,6,Amazon Wholesale India,5.13,59.0,600,2.0
4997,5997,2024-02-22,P022,7,648,4536,Non-stick Frying Pan,Home & Kitchen,393,394,4,ITC Distribution Network,5.42,73.0,537,1.0
4998,5998,2024-05-07,P020,9,581,5229,Blanket,Clothing,357,350,7,Amazon Wholesale India,4.96,71.0,526,2.0
4999,5999,2024-06-28,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06,92.0,501,1.0

In [ ]:
# Risk Classification

In [85]:
def risk_category(days):
    if days < 15:
        return "High Risk"
    elif days < 25:
        return "Medium Risk"
    else:
        return "Low Risk"

df["inventory_risk"] = df["days_of_stock"].apply(risk_category)

In [86]:
df

,order_ID,date,product_ID,units_sold,selling_price,revenue,product_name,category,cost_price,stock_available,lead_time,supplier,daily_avg_sales,days_of_stock,total_sales_product,inventory_turnover,inventory_risk
0,1000,2024-02-23,P030,8,438,3504,Table Lamp,Home & Kitchen,335,130,4,ITC Distribution Network,5.13,25.0,487,4.0,Low Risk
1,1001,2024-03-27,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06,92.0,501,1.0,Low Risk
2,1002,2024-05-08,P009,9,279,2511,Laptop Backpack,Electronics,221,416,2,Flipkart Wholesale,5.18,80.0,534,1.0,Low Risk
3,1003,2024-05-26,P047,2,369,738,Mobile Charger,Electronics,120,456,5,Tata Consumer Distribution,4.73,96.0,478,1.0,Low Risk
4,1004,2024-05-05,P001,9,418,3762,Wireless Mouse,Electronics,202,264,9,D-Mart Supply Services,5.05,52.0,475,2.0,Low Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,5995,2024-06-28,P019,1,465,465,Pillow Cover,Clothing,408,64,8,Metro Cash & Carry India,5.28,12.0,533,8.0,High Risk
4996,5996,2024-04-17,P002,4,515,2060,Mechanical Keyboard,Electronics,448,301,6,Amazon Wholesale India,5.13,59.0,600,2.0,Low Risk
4997,5997,2024-02-22,P022,7,648,4536,Non-stick Frying Pan,Home & Kitchen,393,394,4,ITC Distribution Network,5.42,73.0,537,1.0,Low Risk
4998,5998,2024-05-07,P020,9,581,5229,Blanket,Clothing,357,350,7,Amazon Wholesale India,4.96,71.0,526,2.0,Low Risk
4999,5999,2024-06-28,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06,92.0,501,1.0,Low Risk

In [89]:
(df[df["inventory_risk"] == "Medium Risk"]).count()

order_ID               948
date                   948
product_ID             948
units_sold             948
selling_price          948
revenue                948
product_name           948
category               948
cost_price             948
stock_available        948
lead_time              948
supplier               948
daily_avg_sales        948
days_of_stock          948
total_sales_product    948
inventory_turnover     948
inventory_risk         948
dtype: int64

In [ ]:
# Reorder Point Calculation

In [92]:
df = df.drop(columns = ['reorder_point'])

In [93]:
df

,order_ID,date,product_ID,units_sold,selling_price,revenue,product_name,category,cost_price,stock_available,lead_time,supplier,daily_avg_sales,days_of_stock,total_sales_product,inventory_turnover,inventory_risk
0,1000,2024-02-23,P030,8,438,3504,Table Lamp,Home & Kitchen,335,130,4,ITC Distribution Network,5.13,25.0,487,4.0,Low Risk
1,1001,2024-03-27,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06,92.0,501,1.0,Low Risk
2,1002,2024-05-08,P009,9,279,2511,Laptop Backpack,Electronics,221,416,2,Flipkart Wholesale,5.18,80.0,534,1.0,Low Risk
3,1003,2024-05-26,P047,2,369,738,Mobile Charger,Electronics,120,456,5,Tata Consumer Distribution,4.73,96.0,478,1.0,Low Risk
4,1004,2024-05-05,P001,9,418,3762,Wireless Mouse,Electronics,202,264,9,D-Mart Supply Services,5.05,52.0,475,2.0,Low Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,5995,2024-06-28,P019,1,465,465,Pillow Cover,Clothing,408,64,8,Metro Cash & Carry India,5.28,12.0,533,8.0,High Risk
4996,5996,2024-04-17,P002,4,515,2060,Mechanical Keyboard,Electronics,448,301,6,Amazon Wholesale India,5.13,59.0,600,2.0,Low Risk
4997,5997,2024-02-22,P022,7,648,4536,Non-stick Frying Pan,Home & Kitchen,393,394,4,ITC Distribution Network,5.42,73.0,537,1.0,Low Risk
4998,5998,2024-05-07,P020,9,581,5229,Blanket,Clothing,357,350,7,Amazon Wholesale India,4.96,71.0,526,2.0,Low Risk
4999,5999,2024-06-28,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06,92.0,501,1.0,Low Risk

In [94]:
safety_stock = 30

df["reorder_point"] = ((df["daily_avg_sales"] * df["lead_time"]) + safety_stock).round()

In [95]:
df

,order_ID,date,product_ID,units_sold,selling_price,revenue,product_name,category,cost_price,stock_available,lead_time,supplier,daily_avg_sales,days_of_stock,total_sales_product,inventory_turnover,inventory_risk,reorder_point
0,1000,2024-02-23,P030,8,438,3504,Table Lamp,Home & Kitchen,335,130,4,ITC Distribution Network,5.13,25.0,487,4.0,Low Risk,51.0
1,1001,2024-03-27,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06,92.0,501,1.0,Low Risk,70.0
2,1002,2024-05-08,P009,9,279,2511,Laptop Backpack,Electronics,221,416,2,Flipkart Wholesale,5.18,80.0,534,1.0,Low Risk,40.0
3,1003,2024-05-26,P047,2,369,738,Mobile Charger,Electronics,120,456,5,Tata Consumer Distribution,4.73,96.0,478,1.0,Low Risk,54.0
4,1004,2024-05-05,P001,9,418,3762,Wireless Mouse,Electronics,202,264,9,D-Mart Supply Services,5.05,52.0,475,2.0,Low Risk,75.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,5995,2024-06-28,P019,1,465,465,Pillow Cover,Clothing,408,64,8,Metro Cash & Carry India,5.28,12.0,533,8.0,High Risk,72.0
4996,5996,2024-04-17,P002,4,515,2060,Mechanical Keyboard,Electronics,448,301,6,Amazon Wholesale India,5.13,59.0,600,2.0,Low Risk,61.0
4997,5997,2024-02-22,P022,7,648,4536,Non-stick Frying Pan,Home & Kitchen,393,394,4,ITC Distribution Network,5.42,73.0,537,1.0,Low Risk,52.0
4998,5998,2024-05-07,P020,9,581,5229,Blanket,Clothing,357,350,7,Amazon Wholesale India,4.96,71.0,526,2.0,Low Risk,65.0
4999,5999,2024-06-28,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06,92.0,501,1.0,Low Risk,70.0

In [ ]:
# Reorder Decision (Automation Logic)

In [96]:
df["reorder_flag"] = df.apply(
    lambda x: "Reorder Needed" if x["stock_available"] < x["reorder_point"] else "Sufficient",
    axis=1
)

In [97]:
df

,order_ID,date,product_ID,units_sold,selling_price,revenue,product_name,category,cost_price,stock_available,lead_time,supplier,daily_avg_sales,days_of_stock,total_sales_product,inventory_turnover,inventory_risk,reorder_point,reorder_flag
0,1000,2024-02-23,P030,8,438,3504,Table Lamp,Home & Kitchen,335,130,4,ITC Distribution Network,5.13,25.0,487,4.0,Low Risk,51.0,Sufficient
1,1001,2024-03-27,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06,92.0,501,1.0,Low Risk,70.0,Sufficient
2,1002,2024-05-08,P009,9,279,2511,Laptop Backpack,Electronics,221,416,2,Flipkart Wholesale,5.18,80.0,534,1.0,Low Risk,40.0,Sufficient
3,1003,2024-05-26,P047,2,369,738,Mobile Charger,Electronics,120,456,5,Tata Consumer Distribution,4.73,96.0,478,1.0,Low Risk,54.0,Sufficient
4,1004,2024-05-05,P001,9,418,3762,Wireless Mouse,Electronics,202,264,9,D-Mart Supply Services,5.05,52.0,475,2.0,Low Risk,75.0,Sufficient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,5995,2024-06-28,P019,1,465,465,Pillow Cover,Clothing,408,64,8,Metro Cash & Carry India,5.28,12.0,533,8.0,High Risk,72.0,Reorder Needed
4996,5996,2024-04-17,P002,4,515,2060,Mechanical Keyboard,Electronics,448,301,6,Amazon Wholesale India,5.13,59.0,600,2.0,Low Risk,61.0,Sufficient
4997,5997,2024-02-22,P022,7,648,4536,Non-stick Frying Pan,Home & Kitchen,393,394,4,ITC Distribution Network,5.42,73.0,537,1.0,Low Risk,52.0,Sufficient
4998,5998,2024-05-07,P020,9,581,5229,Blanket,Clothing,357,350,7,Amazon Wholesale India,4.96,71.0,526,2.0,Low Risk,65.0,Sufficient
4999,5999,2024-06-28,P033,9,261,2349,Organic Rice 5kg,Grocery,158,468,8,Flipkart Wholesale,5.06,92.0,501,1.0,Low Risk,70.0,Sufficient

In [ ]:
# Save Final File

In [98]:
df.to_csv("final_inventory_analysis.csv", index=False)